name: 'Maven CLI for the GitHub Actions'
description: 'Use Maven CLI with JDK 8, 11, 13 from a direcory'
branding:
    icon: 'package'
    color: 'green'
inputs:
    lifecycle:
        description: 'Maven lifecycles'
        required: true
        default: 'clean package'
runs:
    using: 'docker'
    image: 'Dockerfile'
    args:
        - ${{ inputs.lifecycle }}
